### PR TITLE
stream quality visibility improved to make it more user friendly

### PR DESCRIPTION
**Pull request by sajjadhossanshimanto**
before

previously video Strem Quality was represented by video hight. But in many case video quality and video hight are not the same [ e.g youtu.be/cd-ozdPSAIA ] . I've solved this with itag property information which I found on another opensouce project

### CODE REVIEW

**Comment by sajjadhossanshimanto** [comment]
Sorry I for forgot about aqality sorting. I'll fix it very soon and make a new commit.

**Comment by pyIDM** [comment]
@sajjadhossanshimanto 
Thanks for your good work
however these itags might be ok for youtube videos, but it is very limited for other video types like hls, for example this link https://bitdash-a.akamaihd.net/content/MI201109210084_1/m3u8s/f08e80da-bf1d-4e3d-8899-f0f6155f6efa.m3u8
is a dash hls video

you can see below format id numbers doesn't exist in itags tables and all lookup values will be zero, 

image

**Comment by pyIDM** [comment]
we can get what we want from format_note field

modifying only this code in video.py will do the trick, and no need to add itags

```
@property
def quality(self):
    try:
        if self.mediatype == 'audio':
            return int(self.abr)
        else:
            match = re.search(r'\d+', self.format_note)
            if match:
                return int(match.group())
            else:
                return int(self.height)
    except:
        return 0
```

**Comment by sajjadhossanshimanto** [comment]
I see.But sir it would be better if you include the itag properties only for YouTube. As it will help  user a lot.

**Comment by sajjadhossanshimanto** [comment]
If you want me to do this job, I can't do this right now. I have some personal issue. I may be free after 5 days from now.

**Comment by pyIDM** [comment]
> I see.But sir it would be better if you include the itag properties only for YouTube. As it will help user a lot.

@sajjadhossanshimanto 
youtube will send itag and quality label (the quality values sent to player e.g. 720p, 1080p, etc...)
youtube-dl extractor "youtube.py" will extract this value in field named "format_note"

here is a  link to the code:
https://github.com/ytdl-org/youtube-dl/blob/84f19c026fc54e8793354a3bf1a1fe634e97e276/youtube_dl/extractor/youtube.py#L1985

also itag tables already included in youtube.py extractor 
https://github.com/ytdl-org/youtube-dl/blob/84f19c026fc54e8793354a3bf1a1fe634e97e276/youtube_dl/extractor/youtube.py#L384

so no need to add itag tables

> If you want me to do this job, I can't do this right now. I have some personal issue. I may be free after 5 days from now.

No need, I will add the code i mentioned above to fix this problem, and once you have time you can make a new pull request for adding only .gitignore file so i can add your name to contributors' list
Thanks for your good work

**Comment by sajjadhossanshimanto** [comment]
Thanks for you time

**Pull request closed without merging**
